# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

trigger: none

pr: none

parameters:
- name: TargetBranch
  displayName: Target branch for ACTS Repo
  type: string
  default: origin/main

- name: TargetTag
  displayName: Target tag for ACTS Repo
  type: string
  default: v1.0.0

variables:
  #- template: ./variables/general_variables.yml
  #- template: ./variables/general_feature_flags.yml
  #- template: ./variables/entra_assignments.yml
  #- template: ./variables/data_science_toolkit.yml
  #- template: ./variables/networking_setup.yml
  #- template: ./variables/consumers/acts_variables.yml
  #- template: ./variables/consumers/beneficial_ownership_variables.yml
  #- template: ./variables/consumers/generic_variables.yml
  - name: environment
    value: 'development'
  - name: envFolderPath
    value: 'dev'
  - name: DeployDataScienceToolkit
    value: 'True'
  - name: AcceleratorGitHubPath
    value: ./ACTS-VAT-Tax-Accelerator/DeliveryIP_GitHub

resources:
  repositories:
  - repository: TestRepo 
    type: github
    endpoint: GitHubBranchTagsTest
    name: Eudora-Li01/TestRepo
    ref: refs/heads/main
    branches:
      include:
        - main
        - test

jobs:
- job: create_env_azure_resources
  displayName: 'Create Environment Azure Resources'
  pool:
    vmImage: 'ubuntu-22.04'
  steps:
  - checkout: self
    persistCredentials: true
    clean: true
    fetchDepth: 1
  # - task: Checkout@2
  #   displayName: 'Checkout repository'
  #   inputs:
  #     repository: $(Build.Repository.Name)
  #     persistCredentials: true
  #     clean: true
  #     fetchDepth: 1
  - task: AzurePowerShell@5
    displayName: 'OIDC Login to Azure Public Cloud with AzPowershell'
    inputs:
      azureSubscription: GitHubBranchTagsTest
      ScriptType: 'InlineScript'
      Inline: |
        Connect-AzAccount -ServicePrincipal -Tenant $(TENANT_ID) -Credential (New-Object System.Management.Automation.PSCredential ('$(SERVICE_PRINCIPAL_CLIENT_ID)', (ConvertTo-SecureString '$(SERVICE_PRINCIPAL_KEY)' -AsPlainText -Force))) -Subscription $(SUBSCRIPTION_ID)
      errorActionPreference: 'stop'
