# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

trigger: none

pr: none

resources:
  repositories:
  - repository: TestRepo 
    type: github
    endpoint: GitHubBranchTagsTest
    name: Eudora-Li01/TestRepo
    ref: refs/heads/main


jobs:
- job: UpdateAndPush
  displayName: 'Update file and push to other branch'
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - checkout: self
    persistCredentials: true
    clean: true
    fetchDepth: 1
    ref: refs/heads/main 

  - script: |
      git checkout test
      echo "Updated content" > updated_file.txt
      git add updated_file.txt
      git commit -m "Update file content"
      git push origin test
    displayName: 'Switch branch and update file'


