trigger: none

pr: none

resources:
  repositories:
  - repository: GitHubBranchTagsTest 
    type: github
    endpoint: GitHubBranchTagsTest
    name: Eudora-Li01/TestRepo
    ref: refs/heads/main

jobs:
- job: Updatebranchtag
  displayName: 'Update branch or tag'
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - checkout: GitHubBranchTagsTest //refs/heads/test
    clean: true
    fetchDepth: 1

  - script: |
      current_branch=$(git rev-parse --abbrev-ref HEAD)
      echo "Current branch is: $current_branch"
    displayName: 'Print current branch'

  - checkout: GitHubBranchTagsTest //refs/tags/v1.0
    clean: true
    fetchDepth: 1

  - script: |
      current_tag=$(git describe --tags --abbrev=0)
      echo "Current tag is: $current_tag"
    displayName: 'Print current tag'
